# Generated by Django 3.2 on 2021-05-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200526_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'Friend', 'verbose_name_plural': 'Friends'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='friend',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatar/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), (None, '-')], max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='status',
            name='online',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Was online'),
        ),
    ]
